In [ ]:
# Pandas is an open source library built on top of NumPy
# Pandas can work with wide variety of data types

In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
np.zeros(10) + 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [14]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [15]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
a = np.arange(9)
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.random.rand(1)

array([0.1189336])

In [20]:
np.random.randn(25)

array([-0.90584322, -0.45807374,  0.91164709,  1.63563109,  0.44024798,
        0.75011133, -1.27107465, -2.22583411, -0.05266561,  0.46219295,
       -1.38251281, -0.97415107,  0.1374997 , -0.9682326 , -1.2284184 ,
        0.97315607,  0.3978492 ,  0.59272927, -0.68958314, -0.751907  ,
        0.40307543, -0.85269567, -1.04532618, -0.25010316,  0.79222372])

In [22]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [23]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [24]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [25]:
mat = np.arange(1,26).reshape(5,5)

In [26]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [30]:
mat[3,4]

20

In [32]:
mat[:3,1]

array([ 2,  7, 12])

In [33]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [35]:
mat[4:,:]

array([[21, 22, 23, 24, 25]])

In [37]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
np.sum(mat)

325

In [39]:
mat.sum()

325

In [40]:
mat.std()

7.211102550927978

In [41]:
np.std(mat)

7.211102550927978

In [42]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [2]:
# Pandas
# Series
# DataFrames
# Missing Data
# GroupBy
# Merging, Joining and Concatenating
# Operations
# Data Input and Output

In [3]:
# Series

In [4]:
import numpy as np
import pandas as pd

In [6]:
# 4 separate Python objects
labels = ['a', 'b', 'c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10, 'b':20, 'c':30}

In [8]:
labels

['a', 'b', 'c']

In [9]:
my_data

[10, 20, 30]

In [10]:
arr

array([10, 20, 30])

In [11]:
d

{'a': 10, 'b': 20, 'c': 30}

In [12]:
pd.Series(data = my_data)

0    10
1    20
2    30
dtype: int64

In [14]:
pd.Series(data=my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [15]:
pd.Series(my_data,labels)

a    10
b    20
c    30
dtype: int64

In [16]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [17]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [18]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [19]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [20]:
pd.Series(data=[sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

In [21]:
# Index

In [24]:
ser1 = pd.Series([1,2,3,4], ['USA', 'Germany', 'USSR', 'Japan'])

In [25]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [26]:
ser2 = pd.Series([1,2,5,4], ['USA', 'Germany', 'Italy', 'Japan'])

In [27]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [28]:
ser1['USA']

1

In [29]:
ser3 = pd.Series(data=labels)

In [31]:
ser3

0    a
1    b
2    c
dtype: object

In [32]:
ser3[0]

'a'

In [35]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [36]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [34]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [38]:
# DataFrames - part1

In [39]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [40]:
# random seed to make sure we have the same random number
np.random.seed(101)

In [42]:
df = pd.DataFrame(randn(5,4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y','Z'])

In [45]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [46]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [47]:
type(df['W'])

pandas.core.series.Series

In [48]:
type(df)

pandas.core.frame.DataFrame

In [50]:
# do NOT use this because it might confuse
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [51]:
df[['W','Z']]

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [57]:
df['new'] = df['W'] + df['Y']

In [58]:
df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [61]:
#df.drop('new')->error

In [60]:
df.drop('new', axis=1)

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [62]:
df

W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [63]:
df.drop('new', axis=1, inplace = True)

In [64]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [65]:
df.drop('E', axis=0)

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [66]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [67]:
df.shape

(5, 4)

In [70]:
# Selecting 1 column
df['Y']

A   -1.706086
B    0.166905
C    0.638787
D   -0.943406
E    0.238127
Name: Y, dtype: float64

In [69]:
# Selecting Columns
df[['Z', 'X']]

Z         X
A -1.159119  1.693723
B  0.184502  0.390528
C  0.329646  0.072960
D  0.484752 -0.754070
E  1.996652  1.901755

In [71]:
# Selecting a Row by a label index
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [74]:
# Selecting a Row by index space location
df.iloc[1]

W   -0.134841
X    0.390528
Y    0.166905
Z    0.184502
Name: B, dtype: float64

In [75]:
df.loc['B','Y']

0.16690463609281317

In [76]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [110]:
# Selecting a subset of DataFrame
# CONDITIONAL SELECTION
df.loc[['A', 'B'],['W', 'Y']]

W         Y
A  0.302665 -1.706086
B -0.134841  0.166905

In [79]:
df > 0

W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [80]:
booldf = df>0

In [81]:
df[booldf]

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [82]:
df[df>0]

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [83]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [84]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [86]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [87]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [85]:
df[df['W']>0]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [89]:
df[df['Z']<0]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119

In [90]:
resultdf = df[df['Z']>0]

In [91]:
resultdf['X']

B    0.390528
C    0.072960
D   -0.754070
E    1.901755
Name: X, dtype: float64

In [93]:
df[df['W']>0]['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [94]:
df[df['W']>0][['X', 'Y']]

X         Y
A  1.693723 -1.706086
C  0.072960  0.638787

In [96]:
boolser = df['W']>0
result = df[boolser]
mycols = ['Y','X']
result[mycols]

Y         X
A -1.706086  1.693723
C  0.638787  0.072960

In [99]:
#df[(df['W']>0) and (df['Y']>1)] -> error

In [101]:
df[(df['W']>0) & (df['Y']>0)]

W        X         Y         Z
C  0.807706  0.07296  0.638787  0.329646

In [102]:
df[(df['W']>0) | (df['Y']>0)]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

In [103]:
df.reset_index()

index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [104]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [105]:
newind = 'CA NY WY OR CO'. split()

In [106]:
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [107]:
df['States'] = newind

In [108]:
df

W         X         Y         Z States
A  0.302665  1.693723 -1.706086 -1.159119     CA
B -0.134841  0.390528  0.166905  0.184502     NY
C  0.807706  0.072960  0.638787  0.329646     WY
D -0.497104 -0.754070 -0.943406  0.484752     OR
E -0.116773  1.901755  0.238127  1.996652     CO

In [109]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      0.302665  1.693723 -1.706086 -1.159119
NY     -0.134841  0.390528  0.166905  0.184502
WY      0.807706  0.072960  0.638787  0.329646
OR     -0.497104 -0.754070 -0.943406  0.484752
CO     -0.116773  1.901755  0.238127  1.996652

In [111]:
# DATAFRAMES - PART 3

In [112]:
# Multi Index

In [113]:
import numpy as np
import pandas as pd

In [114]:
# Index levels
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [115]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [116]:
inside

[1, 2, 3, 1, 2, 3]

In [117]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [118]:
list(zip(outside, inside))

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [119]:
df = pd.DataFrame(randn(6,2), hier_index, ['A', 'B'])

In [120]:
df

A         B
G1 1 -0.993263  0.196800
   2 -1.136645  0.000366
   3  1.025984 -0.156598
G2 1 -0.031579  0.649826
   2  2.154846 -0.610259
   3 -0.755325 -0.346419

In [121]:
df.loc['G1']

A         B
1 -0.993263  0.196800
2 -1.136645  0.000366
3  1.025984 -0.156598

In [122]:
df.loc['G1'].loc[1]

A   -0.993263
B    0.196800
Name: 1, dtype: float64

In [124]:
df.index.names = ['Groups', 'Num']

In [125]:
df

A         B
Groups Num                    
G1     1   -0.993263  0.196800
       2   -1.136645  0.000366
       3    1.025984 -0.156598
G2     1   -0.031579  0.649826
       2    2.154846 -0.610259
       3   -0.755325 -0.346419

In [126]:
df.loc['G2']

A         B
Num                    
1   -0.031579  0.649826
2    2.154846 -0.610259
3   -0.755325 -0.346419

In [130]:
df.loc['G2'].loc[2]

A    2.154846
B   -0.610259
Name: 2, dtype: float64

In [129]:
df.loc['G2'].loc[2]['B']

-0.6102588558227414

In [131]:
df.xs

<bound method NDFrame.xs of                    A         B
Groups Num                    
G1     1   -0.993263  0.196800
       2   -1.136645  0.000366
       3    1.025984 -0.156598
G2     1   -0.031579  0.649826
       2    2.154846 -0.610259
       3   -0.755325 -0.346419>

In [133]:
df.loc['G1']

A         B
Num                    
1   -0.993263  0.196800
2   -1.136645  0.000366
3    1.025984 -0.156598

In [134]:
df.xs('G1')

A         B
Num                    
1   -0.993263  0.196800
2   -1.136645  0.000366
3    1.025984 -0.156598

In [135]:
df.xs(1,level='Num')

A         B
Groups                    
G1     -0.993263  0.196800
G2     -0.031579  0.649826

In [136]:
# MISSING DATA

In [137]:
d = {'A':[1,2,np.nan], 'B': [5, np.nan, np.nan], 'C':[1,2,3]}

In [138]:
df = pd.DataFrame(d)

In [139]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [140]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [141]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [143]:
# at least 2 (not nan value)
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [144]:
df.fillna(value='FILL VALUE')

A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [146]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [147]:
# GROUPBY


In [150]:
data = {'Company':['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'], 'Person':['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'], 'Sales': [200,120,340,124,243,350]}

In [151]:
df = pd.DataFrame(data)

In [152]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [154]:
byComp = df.groupby(['Company'])

In [155]:
byComp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [156]:
byComp.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [157]:
byComp.sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [158]:
df.groupby('Company').sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [159]:
df.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [160]:
df.groupby('Company').min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [161]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [162]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [163]:
df.groupby('Company').describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

In [164]:
# MERGING, JOINING AND CONCATENATING

In [165]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])

In [166]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 

In [169]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [167]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [168]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [170]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [173]:
# CONCATENATION
# Concatenation basically glues together DataFrames. dimensions should match along the axis we are concatenating on
# Use pd.concat and pass a list of DataFrames to concatenate together

In [172]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [175]:
pd.concat([df1,df2,df3], axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [176]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})    

In [177]:
left

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [178]:
right

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [179]:
# MERGING

In [180]:
pd.merge(left,right,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [181]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [182]:
left

key1 key2   A   B
0   K0   K0  A0  B0
1   K0   K1  A1  B1
2   K1   K0  A2  B2
3   K2   K1  A3  B3

In [183]:
right

key1 key2   C   D
0   K0   K0  C0  D0
1   K1   K0  C1  D1
2   K1   K0  C2  D2
3   K2   K0  C3  D3

In [184]:
pd.merge(left,right,on=['key1', 'key2'])

key1 key2   A   B   C   D
0   K0   K0  A0  B0  C0  D0
1   K1   K0  A2  B2  C1  D1
2   K1   K0  A2  B2  C2  D2

In [185]:
pd.merge(left,right,how='outer', on=['key1', 'key2'])

key1 key2    A    B    C    D
0   K0   K0   A0   B0   C0   D0
1   K0   K1   A1   B1  NaN  NaN
2   K1   K0   A2   B2   C1   D1
3   K1   K0   A2   B2   C2   D2
4   K2   K1   A3   B3  NaN  NaN
5   K2   K0  NaN  NaN   C3   D3

In [186]:
pd.merge(left,right,how='right', on=['key1', 'key2'])

key1 key2    A    B   C   D
0   K0   K0   A0   B0  C0  D0
1   K1   K0   A2   B2  C1  D1
2   K1   K0   A2   B2  C2  D2
3   K2   K0  NaN  NaN  C3  D3

In [187]:
pd.merge(left,right,how= 'left', on=['key1', 'key2'])

key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN

In [189]:
# JOINING

In [190]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [192]:
left

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [193]:
right

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [195]:
# automaticly inner join
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [196]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [197]:
# OPERATIONS

In [198]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [199]:
df['col2'].unique()

array([444, 555, 666])

In [200]:
len(df['col2'].unique())

3

In [201]:
df['col2'].nunique()

3

In [202]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [204]:
df['col1']>2

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [206]:
df[(df['col1']>2) & (df['col2']==444)]

col1  col2 col3
3     4   444  xyz

In [207]:
# APPLY METHOD

In [208]:
def times2(x):
    return x*2

In [209]:
df['col1'].sum()

10

In [210]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [212]:
df['col3'].apply

<bound method Series.apply of 0    abc
1    def
2    ghi
3    xyz
Name: col3, dtype: object>

In [211]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [213]:
df['col2'].apply(lambda x:x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [214]:
df.drop('col1', axis=1)

col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

In [216]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [217]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [218]:
df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [219]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [220]:
df.sort_values(by='col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [221]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [222]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [223]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [224]:
df.pivot_table(values='D', index=['A','B'], columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [225]:
# DATA INPUT & OUTPUT

In [226]:
# CSV
# Excel
# HTML
# SQL

In [228]:
pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1')

/Users/maiango/anaconda3/envs/learn-env/lib/python3.6/site-packages/pandas/io/excel.py:329: FutureWarning: The `sheetname` keyword is deprecated, use `sheet_name` instead
  **kwds)


a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [231]:
# CSV INPUT:
# pd.read_csv('example.csv')

In [232]:
# CSV OUTPUT:
# df.to_csv('example',index=False)

In [233]:
# EXCEL:
# Might need to install conda install xlrd

# EXCEL INPUT:
# pd.read_excel('Excel_Sample.xlsx',sheetname='Sheet1')

In [234]:
# EXCEL OUTPUT:
# df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

In [235]:
# HTML
# You may need to install htmllib5,lxml, and BeautifulSoup4. In your terminal/command prompt run:

# conda install lxml
# conda install html5lib
# conda install BeautifulSoup4
# Then restart Jupyter Notebook. (or use pip install if you aren't using the Anaconda Distribution)

# Pandas can read table tabs off of html. For example:

In [236]:
# HTML INPUT
# Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

# df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [ ]:
# from sqlalchemy import create_engine
# engine = create_engine('sqlite:///:memory:')
# df.to_sql('data', engine)
# sql_df = pd.read_sql('data',con=engine)
